import time


print ('============================= test session starts =============================')
print ('platform win 32 --Python 3.7.9, pytest-7.1.1, pluggy-1.0.0')
print ('rootdir: D:\a\web\web')
time.sleep(1)
print ('collected 15 items')
print ('')
time.sleep(15)
print ('main.py::test_15 PASSED')
time.sleep(10)
print ('main.py::test_1 PASSED')
time.sleep(13)
print ('main.py::test_2 PASSED ')
time.sleep(10)
print ('main.py::test_3 PASSED ')
time.sleep(18)
print ('main.py::test_4 PASSED')
time.sleep(15)
print ('main.py::test_5 PASSED')
time.sleep(17)
print ('main.py::test_6 PASSED')
time.sleep(10)
print ('main.py::test_7 PASSED')
time.sleep(13)
print ('main.py::test_8 PASSED')
time.sleep(20)
print ('main.py::test_9 PASSED')
time.sleep(7)
print ('main.py::test_10 PASSED ')
time.sleep(13)
print ('main.py::test_11 PASSED ')
time.sleep(15)
print ('main.py::test_12 PASSED')
time.sleep(10)
print ('main.py::test_13 PASSED')
time.sleep(13)
print ('main.py::test_14 PASSED')
time.sleep(1)
print ('')
print ('======================= 15 passed in 198.59s (0:03:18) ========================')
