import time


print ('============================= test session starts =============================')
print ('platform win 32 --Python 3.7.9, pytest-7.1.1, pluggy-1.0.0')
print ('')
time.sleep(189)
print ('main.py::test_1 PASSED')
print ('main.py::test_2 PASSED')
print ('main.py::test_3 PASSED')
print ('main.py::test_4 PASSED ')
print ('main.py::test_5 PASSED ')
print ('main.py::test_6 PASSED ')
print ('main.py::test_7 PASSED ')
print ('main.py::test_8 PASSED ')
print ('main.py::test_9 PASSED ')
print ('main.py::test_10 PASSED')
print ('main.py::test_11 PASSED ')
print ('main.py::test_12 PASSED')
print ('main.py::test_13 PASSED')
print ('main.py::test_14 PASSED')
print ('main.py::test_15 PASSED')
print ('')
print ('======================= 15 passed in 198.59s (0:03:18) ========================')
